const express=require('express')
const usercontroller=require('../controllers/usersController')
const doctorcontroller=require('../controllers/doctorcontroller')
const jwtmiddleware=require('../middlewares/jwtmiddle')
const multermiddleware=require('../middlewares/multermiddle')
const appointmentcontroller=require('../controllers/appointmentcontroller')
const rolecheckmiddle=require('../middlewares/rolemiddle')
const paypalpaymentcontroller=require('../controllers/paypalcontroller')
const postcontroller=require('../controllers/postcontroller')
const profilecontroller=require('../controllers/profilecontroller')

const route=express.Router()
route.post('/reg',usercontroller.userRegister)
route.post('/log',usercontroller.userlogin)
route.post('/adddoc',jwtmiddleware,rolecheckmiddle(['admin']),multermiddleware.single('image'),doctorcontroller.addDoctor)
route.get('/getdoc',doctorcontroller.getdoctor)
route.get('/finddoc/:doctorid',doctorcontroller.getdoctorByid)
route.get('/spcdoc/:specialization',doctorcontroller.getdoctorbyspecialization)
route.post('/takeappo',jwtmiddleware,appointmentcontroller.doctorappointment)
route.get('/getmyappo',jwtmiddleware,appointmentcontroller.getmyappointment)
route.delete('/deletedoc/:doctorid',jwtmiddleware,rolecheckmiddle(['admin']),doctorcontroller.deletedoctor)
route.put('/editdoc/:doctorid',jwtmiddleware,rolecheckmiddle(['admin']),multermiddleware.single('image'),doctorcontroller.editdoctor)
route.get('/docprofile',jwtmiddleware,doctorcontroller.getDoctorDashboard)
route.get('/allappo',jwtmiddleware,rolecheckmiddle(['admin']),appointmentcontroller.getallappointments)
route.delete('/deleteappo/:appointmentid',jwtmiddleware,rolecheckmiddle(['admin']),appointmentcontroller.deleteappointment)

// route.get('/searchappo',jwtmiddleware,rolecheckmiddle(['admin']),appointmentcontroller.searchappointment)
route.post('/payment/create',paypalpaymentcontroller.createPayment)
route.get('/payment/success',paypalpaymentcontroller.executePayment)
route.get('/payment/cancel',paypalpaymentcontroller.cancelPayment)
route.post('/addpost',jwtmiddleware,postcontroller.addpost)
route.get('/getallpost',jwtmiddleware,postcontroller.getallpost)
route.get('/getpost/:userid',jwtmiddleware,postcontroller.getindividualpost)
route.delete('/deletepost/:postid',jwtmiddleware,postcontroller.deletepost)
route.post('/addprofile',jwtmiddleware,multermiddleware.single('image'),profilecontroller.addprofile)
route.get('/getprofile/:userid',jwtmiddleware,profilecontroller.getprofile)
route.put('/likepost/:postid',jwtmiddleware,postcontroller.likePost)
route.get('/getprofileonland',profilecontroller.getprofileonlanding)
route.put('/updateprofile',jwtmiddleware,multermiddleware.single('image'),profilecontroller.updateProfile)
module.exports=route